workflows:
  ios-build:
    name: Build iOS App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.leoklinger.flowin" # substitua pelo seu bundle ID real
    scripts:
      - name: Install dependencies
        script: |
          cd src
          flutter pub get
      - name: Flutter build iOS
        script: |
          cd src
          flutter build ipa --release --no-codesign --no-tree-shake-icons
    artifacts:
      - src/build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - leandro.klingeroliveira@gmail.com
